version: "3"

services:
  strapi-api:
    image: strapi/strapi
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: backend/.env
    working_dir: /app
    depends_on:
      - postgres
    networks:
      - strapi-app-network
    volumes:
      - ./backend/:/app/
    ports:
      - "80:1337"
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - database:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - backend/.env
    networks:
      - strapi-app-network

networks:
  strapi-app-network:
    driver: bridge

volumes:
  database:
